# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: inmar devBlog
email: developers@inmar.com
description: > # this means to ignore newlines until "baseurl:"
  This is a blog for developers at inmar. Add markdown posts to the repository!
baseurl: "/devblog" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: blackWookie91
github_username:  pnjoku

# Build settings
markdown: kramdown
